title: "Midwest Data Librarian Symposium"
description: Website for Midwest Data Librarian Symposium.
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
# baseurl: "/home"
url: https://mw-data-lib-symposium.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
